# Generated by Django 2.2.1 on 2019-07-05 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0001_initial'),
        ('customergroups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('po', models.CharField(max_length=30)),
                ('po_date', models.DateField()),
                ('po_type', models.CharField(max_length=30)),
                ('handled_by', models.CharField(max_length=30)),
                ('project_id', models.CharField(max_length=30, unique=True)),
                ('source', models.CharField(max_length=30)),
                ('invoice_no', models.CharField(max_length=30, null=True)),
                ('invoice_date', models.DateField(null=True)),
                ('warranty_date', models.DateField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.Country')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.District')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customergroups.CustomerGroup')),
                ('site_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customergroups.Site')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.State')),
            ],
            options={
                'verbose_name': 'Customer Project',
                'verbose_name_plural': 'Customer Projects',
            },
        ),
    ]
