# Generated by Django 2.2.1 on 2019-07-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerprojects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproject',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerproject',
            name='po',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customerproject',
            name='po_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customerproject',
            name='po_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customerproject',
            name='sector',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customerproject',
            name='source',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
