# Generated by Django 2.2.1 on 2019-07-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerprojects', '0002_auto_20190709_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproject',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerproject',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerproject',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customerproject',
            name='po',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customerproject',
            name='po_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerproject',
            name='po_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customerproject',
            name='project_id',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='customerproject',
            name='sector',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customerproject',
            name='source',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customerproject',
            name='warranty_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
