# Generated by Django 2.2.1 on 2019-07-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerprojects', '0003_auto_20190710_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproject',
            name='handled_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
