# Generated by Django 2.2.1 on 2019-07-05 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customerprojects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelPartener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_partener', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Channel Partener',
                'verbose_name_plural': 'Channel Parteners',
            },
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Engineer',
                'verbose_name_plural': 'Engineer',
            },
        ),
        migrations.CreateModel(
            name='SalesManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_manager', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Sales Manager',
                'verbose_name_plural': 'Sales Managers',
            },
        ),
        migrations.CreateModel(
            name='Handle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='customerprojects.CustomerProject')),
            ],
            options={
                'verbose_name': 'Assign project',
                'verbose_name_plural': 'Assign projects',
            },
        ),
    ]
