# Generated by Django 2.2.1 on 2019-06-04 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_admin_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_service_manager',
            field=models.BooleanField(default=False, verbose_name='service_manager status'),
        ),
        migrations.CreateModel(
            name='ServiceManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
