# Generated by Django 2.2.1 on 2019-07-05 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customerprojects', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_details', models.CharField(max_length=30)),
                ('warranty', models.DateField()),
                ('warranty_type', models.CharField(max_length=30)),
                ('product_code', models.CharField(max_length=30)),
                ('serial_no', models.CharField(max_length=30)),
                ('comments', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerprojects.CustomerProject')),
            ],
            options={
                'verbose_name': 'CustomerOrder',
                'verbose_name_plural': 'CustomerOrders',
            },
        ),
    ]
