# Generated by Django 2.2.1 on 2019-07-05 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignProject', '0001_initial'),
        ('customerorders', '0001_initial'),
        ('customerprojects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=30, unique=True)),
                ('request_type', models.CharField(max_length=30, unique=True)),
                ('source', models.CharField(max_length=30, unique=True)),
                ('comments', models.TextField(null=True)),
                ('status', models.CharField(max_length=30, unique=True)),
                ('scheduled_date', models.DateTimeField(null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('stop_date', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignProject.Engineer')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customerorders.CustomerOrder')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerprojects.CustomerProject')),
                ('sales_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignProject.SalesManager')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('expense', models.DecimalField(decimal_places=2, default=0.0, max_digits=30, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket')),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
            },
        ),
    ]
