# Generated by Django 2.2.1 on 2019-07-05 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='engineer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignProject.Engineer'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sales_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignProject.SalesManager'),
        ),
    ]
