# Generated by Django 2.2.1 on 2019-07-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20190705_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='request_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='source',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
