# Generated by Django 2.2.1 on 2019-07-05 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customerprojects', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='POC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=30)),
                ('poc_name', models.CharField(max_length=30)),
                ('mobile_1', models.CharField(max_length=10)),
                ('mobile_2', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerprojects.CustomerProject')),
            ],
            options={
                'verbose_name': 'POC',
                'verbose_name_plural': 'POCs',
            },
        ),
    ]
